### ISSUE TITLE
Map dissapears

### ISSUE THREAD

**Issue by WhitexHat** [Roblox/avatar-evolution#4] opened 2019-12-13 20:23 UTC
Basically, if I turn on the setting "LegacyOutlines" from lighting, parts dissapear.

https://gyazo.com/4f69a899b3c918b3fb36e1460834a8ff

**Comment by evaera** [comment] 2019-12-13 22:28
This is a duplicate of #1

**Comment by jbrosnihan-roblox** [comment] 2019-12-14 20:57
closed as duplicate

**Closed** 2019-12-14 20:57 UTC
